import type { Metadata } from "next";
import {Poppins} from "next/font/google"
import "./globals.css";
import Navbar from "@/components/Navbar";



export const metadata: Metadata = {
  title: "Dorbesh",
  description: "Generated by mazahrul islam ",
};


const primary_font=Poppins({weight:"400",style:"normal",subsets:["latin"]})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${primary_font.className}  antialiased`}
      >
     

       <div className="md:w-[90%]   mx-auto">
     <div className="w-[90%] mx-auto">
     <Navbar/>
     </div>
       {children}
       </div>


      </body>
    </html>
  );
}
